version: '3.8'

services:
  deepseek-ocr:
    build: .
    container_name: deepseek-ocr
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - FLASK_ENV=production
      - ALPHAXIV_API_URL=https://api.alphaxiv.org/models/v1/deepseek/deepseek-ocr/inference
    restart: unless-stopped
